/*
 * This source file was generated by the Gradle 'init' task
 */
package org.hyperview;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        // No unit tests
    }
}
